sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t slavomirMatuska/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true slavomirMatuska/docker-react npm run test -- --coverage
